spring.main.web-application-type=none
spring.ai.mcp.server.transport=STDIO

# Disable logs to standard out to avoid breaking the MCP STDIO communication
spring.main.banner-mode=off
logging.level.root=off
logging.level.org.springframework=off
logging.level.com.example=off

# Optionally, redirect logging to a file so we can still debug the server if needed
logging.file.name=mcp-server-spring.log
logging.level.root=info
